# Generated by Django 6.0.6 on 2026-06-17 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_created_at'),
        ('orders', '0003_alter_order_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_owner', to='customer.customer'),
        ),
    ]
