# Generated by Django 6.0.6 on 2026-06-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_owner'),
        ('products', '0002_product_title'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ordereditem',
            constraint=models.UniqueConstraint(fields=('product', 'owner'), name='unique_cart_item'),
        ),
    ]
